[project]
name = "objectable-content"
version = "0.1.0"
description = "Examples and my own additions to the lecture 'Objectable Python'"
readme = "README.md"
requires-python = "==3.12.5"
dependencies = [
    "pandas>=2.0.3",
]

[dependency-groups]
dev = [
    "ruff>=0.9.2",
]